# Generated by Django 4.1 on 2022-09-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
